#!/usr/bin/env python3
"""Render the reviewed screen report from safe, compact numeric evidence only."""
import argparse,collections,datetime,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from gearshift.early_handoff import read,CONDITIONS
from scripts.early_handoff_report import csv_write

def main():
 p=argparse.ArgumentParser();p.add_argument('--results',type=Path,default=ROOT/'results/early_handoff_01');p.add_argument('--report',type=Path,default=ROOT/'EARLY_HANDOFF_RESULTS.md');a=p.parse_args()
 s=read(a.results/'summary.json');sen=read(a.results/'missingness_sensitivity.json');audit=read(a.results/'audit.json');compact=read(a.results/'analysis_input.json');records=compact['records'];d=compact['declaration'];work=audit['actual_study_work']
 # This interpretation is specific to this completed screen, not an automatic claim on future runs.
 assert [s['conditions'][c]['passed'] for c in CONDITIONS]==[96,96,95,105,105,106,106]
 assert [s['conditions'][c]['missing'] for c in CONDITIONS]==[0,0,2,3,3,3,2]
 assert audit['generation_recovery_attempts']==0 and audit['scoring']['kernel_oom_kill_events']==27
 def pct(x):return f'{100*x:.2f}'
 def span(values):return ' to '.join(pct(x) for x in values)
 def mean(c,key):return float(np.mean([r[key] for r in records if r['condition']==c]))
 aggregate=[]
 for c,v in s['conditions'].items():
  row={'condition':c,**{k:v[k] for k in ['passed','draws','missing','pass_rate','quality_lower_bound','quality_upper_bound','mean_stage_seconds']}}
  for key in ['source_token_index','receiver_prefill_tokens','receiver_reasoning_tokens','answer_tokens','total_generated_tokens','source_prefix_accounted_seconds','receiver_prefill_seconds','receiver_reasoning_seconds','answer_seconds','bridge_seconds','clone_seconds','transfer_seconds','answer_output_characters']:
   row[key+'_mean']=mean(c,key)
  aggregate.append(row)
 csv_write(a.results/'condition_summary.csv',aggregate)
 paired=[]
 for k,v in sen['contrasts'].items():
  primary=s['contrasts'][k]
  paired.append({'comparison':k,'primary_difference':primary['difference'],'primary_ci_low':None if primary['ci95'] is None else primary['ci95'][0],'primary_ci_high':None if primary['ci95'] is None else primary['ci95'][1],'difference_bound_low':v['difference_identification_bounds'][0],'difference_bound_high':v['difference_identification_bounds'][1],'bootstrap_envelope_low':v['task_bootstrap_sensitivity_envelope'][0],'bootstrap_envelope_high':v['task_bootstrap_sensitivity_envelope'][1],**{key:v[key] for key in ['definite_task_gains','definite_task_losses','definite_task_ties','ambiguous_tasks']},'mean_seconds_difference':primary['mean_seconds_difference'],'seconds_ci_low':primary['seconds_difference_ci95'][0],'seconds_ci_high':primary['seconds_difference_ci95'][1],'latency_ratio':primary['latency_ratio']})
 csv_write(a.results/'paired_comparisons.csv',paired)
 lines=['# Early text handoff: completed development screen',
 '', '**Decision: a 50% handoff is a plausible quality/latency candidate, not a validated improvement or a deployable policy.** It uses half the source reasoning tokens and has 87.50–90.00% possible success versus 80.00% small-only, at 1,050.40 s reconstructed stage time versus 533.15 s. It is 34.86% faster than large-only and 32.49% faster than full-text handoff under local stage accounting. But 13 missing scores on one task, only 40 reused development tasks, and broad paired uncertainty prevent a quality-equivalence or generalization claim. Small-only remains the cheapest measured option. No new experiment is authorized by this report.',
 '', '## Scope, provenance and frozen protocol',
 '', 'All **40 original development IDs**, in original membership order, were used; none was selected or dropped after results. The exact ordered list, source-row hashes, platform/difficulty metadata, pins and sampling contract are in [`declaration.json`](configs/early_handoff_01/declaration.json). Per-task outcomes are in [`task_outcomes.csv`](results/early_handoff_01/task_outcomes.csv). These are previously inspected development tasks, **not fresh confirmation**. The declaration’s PLANNED_PREFLIGHT_NOT_LAUNCHED status is the preserved pre-run document, not live status.',
 '', f"Generation implementation: `{audit['generation_implementation_commit']}`. All 840 answers and 1,680 sealed answer/record file hashes and sizes were verified. The audit also checks every prompt/prefix/answer contract, seed, source trajectory identity, score identity and the exact task × condition × draw inventory. Scoring started only after the full generation seal. The final safe code/report commit is recorded in the review ZIP’s `MANIFEST.json` (a report cannot embed its own commit hash).",
 '', '| Dependency | Exact pin |','|---|---|',
 f"| Qwen/Qwen3-32B | `{d['models']['source']['revision']}` |",f"| Qwen/Qwen3-8B | `{d['models']['receiver']['revision']}` |",
 '| LiveCodeBench official code_generation_lite, release_v6 | `0fe84c3912ea0c4d4a78037083943e8f0c4dd505` |',
 '| tokenizer.json SHA256, shared | `aeb13307a71acd8fe81861d94ad54ab689df773318809eed3cbe794b4492dae4` |',
 '| tokenizer_config.json SHA256 | `d5d09f07b48c3086c508b30d1c9114bd1189145b74e982a265350c923acd8101` |',
 '', 'Official upstream benchmark files, task identities/row hashes and all 22 model shards were verified locally. No private archive artifacts are required. LiveCodeBench text/tests, reversible token arrays and raw answers are **not redistributed**. HumanEval+ attribution and the public release remain unchanged.',
 '', 'Hardware: local Apple M4 Max, 128 GB, macOS 27.0; Python 3.12.4, torch 2.14.0, Transformers 4.57.6, nonquantized BF16 MPS/SDPA, batch 1, 512-token initial prefill chunks. One model was resident at a time. Both models passed synthetic bitwise replay/RNG continuation and 36,865-token prefill gates before benchmark work. This is not an H200 replication.',
 '', 'For each task: one source reasoning trajectory; six receiver conditions at **0/10/25/50/75/100%** plus LARGE_ONLY; three fixed final-answer draws per condition. Fractions use `floor(f × L)` of actual source reasoning tokens, excluding the closing-think token, without moving syntactically awkward cuts. Intermediate conditions receive only the original prompt plus the exact prefix and **continue reasoning**. FULL_TEXT replays the whole reasoning prefix natively and answers. No cache translation, source final answer, future reasoning, extra instruction or router is given to the receiver.',
 '', 'Sampling: temperature 0.6, top-p 0.95, top-k 20, min-p 0, repetition penalty 1, presence penalty 0; deterministic algorithms enabled. Source reasoning cap 24,576 tokens; receiver continuation cap 24,576 minus the source prefix; answer cap 4,096; total limit 40,960. All caps remain in results. Fixed SHA256-derived seeds use `early_handoff_01|task_id|draw_index|stream`, first eight bytes modulo 2^63. Receiver reasoning seed is shared across fractions; receiver answer seed is matched by draw across fractions. Source streams are separate. Three draws share a single reasoning history and are not three independent tasks.',
 '', '## All fixed-condition results',
 '', 'Success is the equal-task average of three answer scores. Each condition has 120 planned draws. For conditions with missing scores, exact rates and primary quality CIs remain **null**, as specified before the run. The displayed range is **partial-identification bounds**: missing answers all fail versus all pass, with the original denominator. It is not a confidence interval. No missing answer is silently treated as a failure or removed.',
 '', '| Condition | Pass / fail / missing | Success or bounds (%) | Mean reconstructed seconds | Source body tokens | Receiver reasoning tokens | Answer tokens |', '|---|---:|---:|---:|---:|---:|---:|']
 for c,v in s['conditions'].items():
  q=pct(v['pass_rate']) if v['pass_rate'] is not None else span([v['quality_lower_bound'],v['quality_upper_bound']])
  lines.append(f"| {c} | {v['passed']} / {120-v['passed']-v['missing']} / {v['missing']} | {q} | {v['mean_stage_seconds']:.2f} | {mean(c,'source_token_index'):.2f} | {mean(c,'receiver_reasoning_tokens'):.2f} | {mean(c,'answer_tokens'):.2f} |")
 lines+=['', 'SMALL_ONLY and H10 each have task-cluster 95% success intervals of **67.50–92.50%**. These wide exploratory intervals matter. Numeric tables retain all unrounded values, scalar output lengths, caps, seeds and provenance hashes.',
 '', '![Local quality/latency accounting](results/early_handoff_01/frontier.png)',
 '', '## Paired task comparisons and missingness sensitivity',
 '', 'Primary inference uses **10,000 paired task-cluster resamples**, frozen PCG64 seed 20260922. Every draw for a sampled task stays together; comparisons use the same resampled tasks. Intervals are exploratory and unadjusted for multiple comparisons. With complete coverage H10 minus SMALL_ONLY is **0.00 percentage points (95% CI −7.50 to +7.50)**: one improved task, one worsened task and 38 ties.',
 '', 'The pre-run primary quality comparisons touching missing outcomes remain null in `summary.json`. To make the incomplete screen interpretable, the following **explicitly post-run sensitivity analysis** keeps all 40 tasks and bounds every missing score. Its envelope takes the 2.5th percentile of adverse-completion paired bootstraps and the 97.5th percentile of favorable-completion paired bootstraps. This combines missingness and task sampling sensitivity; it is not an equivalence test or a conventional CI around an identified effect. No scoring or generation was changed.',
 '', '| Comparison | Mean difference bounds (pp) | Bootstrap sensitivity envelope (pp) | Definite gain / loss / tie / ambiguous tasks | Latency ratio |', '|---|---:|---:|---:|---:|']
 for k,v in sen['contrasts'].items():
  counts=' / '.join(str(v[x]) for x in ['definite_task_gains','definite_task_losses','definite_task_ties','ambiguous_tasks'])
  lines.append(f"| {k} | {span(v['difference_identification_bounds'])} | {span(v['task_bootstrap_sensitivity_envelope'])} | {counts} | {s['contrasts'][k]['latency_ratio']:.3f} |")
 lines+=['', 'All paired stage-time differences and their task-cluster intervals are in [`paired_comparisons.csv`](results/early_handoff_01/paired_comparisons.csv). H50 versus LARGE_ONLY is −562.04 s (95% interval −723.18 to −414.23); versus FULL_TEXT, −505.59 s (−665.20 to −360.99). Those intervals describe these reconstructed local timings, not serving-system speedups.',
 '', '## Answers to the six research questions',
 '', '**A. Does early handoff materially outperform small-only?** In this sample, H50 and H75 each improve success by **7.50–10.00 pp** under any completion of missing scores. Each has three definite task gains and no definite losses versus SMALL_ONLY. But the sensitivity envelope is **0 to +20 pp**; this is a development signal, not established out-of-sample superiority. H10 is flat and H25 is within ±0.83 pp.',
 '', '**B. Does it approach large-only/full-text while avoiding source work?** H50 uses 4,329.33 instead of 8,659.08 mean source body tokens and has success bounds close to both references. It reduces the local stage sum by **34.86% versus large-only** and **32.49% versus full-text**. Quality differences remain −2.50 to +1.67 pp versus large-only and −3.33 to +1.67 pp versus full-text, with much wider sampling envelopes. “Approaches in this sample” is justified; “equivalent quality” is not.',
 '', '**C. Is there a potentially useful Pareto improvement?** H50 is the main candidate, but no confirmed dominance of the high-quality references is established. SMALL_ONLY empirically dominates H10 in aggregate: identical quality, with H10 taking 17.86% more time than SMALL_ONLY. H50 and H75 have the same observed pass count, with H50 faster, but their missing outcomes prevent identified quality equality. The frozen exact-score frontier lists only SMALL_ONLY because it excludes every incomplete condition; that is **not** evidence that all early conditions are dominated. The missingness-sensitive potential frontier includes SMALL_ONLY, H25, H50, H75, FULL_TEXT and LARGE_ONLY. This broad set reflects unresolved quality, not six recommendations.',
 '', '**D. How much source reasoning can be removed before quality collapses?** There is no catastrophic collapse: even 0% scores 80%. Removing half the source trace retains the high-quality range in this sample; removing 75–90% returns to roughly small-only quality. The quality increase lies between the tested 25% and 50% points. There is no measured universal threshold between them, and no monotone per-task guarantee.',
 '', '**E. Does the receiver compensate?** Yes. Mean receiver reasoning grows from **0 at full-text** to **2,264 tokens at 75%, 4,845 at 50%, 6,585 at 25%, 7,941 at 10%, and 8,815 at 0%**. H50 has **9,788 total generated body/answer tokens**, more than full-text’s **9,277**, despite fewer source tokens. It saves time because more work runs on the faster receiver, not because total generated work disappears. Full-text prefill is 14.76 s, under 1% of its 1,555.99 s stage sum; early source substitution remains the larger lever.',
 '', '**F. Are gains/failures task-specific or predictable?** They are heterogeneous, but predictability was not tested. `leetcode/3413` gains at every nonzero fraction, `leetcode/3455` at 50% and above, `leetcode/3482` scores 3/3 at H50 but 0/3 at H75 and 1/3 at full/large, and `leetcode/3454` only gains at 75%/full/large. H10 loses `leetcode/3466`; H25 loses `atcoder/abc353_e` and one draw on `leetcode/3450`. These are retrospective descriptions, not validated features or a router. No semantic/predictive claim is inferred from hidden tests.',
 '', '## Retrospective oracle — not a deployable result',
 '', 'The frozen full-population point oracle remains null because of missingness. A post-run supplementary quality-first, latency-tiebreak oracle over fraction conditions (not LARGE_ONLY) has an all-40-task success range of **90.00–92.50%**. On the explicitly labeled **39 fully scored tasks**, excluding only `atcoder/abc364_e` from this supplemental calculation, its same-draw success is **92.31%**, at **569.01 s** mean reconstructed time. Choices: SMALL_ONLY 27 tasks, H10 9, H50 2, H75 1. The excluded task is retained in every primary table and all-population bound. Per-task selections are in `missingness_sensitivity.json`.',
 '', 'This oracle uses outcome knowledge and future total source length; the same three draws select and evaluate each choice. Its apparent opportunity is optimistic and can include timing noise. It does not show that an online selector can recognize those tasks, and it is not directly comparable to a full-40-task point estimate. No policy was trained.',
 '', '## Timing and economic accounting',
 '', 'Per-output accounting sums **source prefix time + receiver native prefill + receiver continuation + one final answer + native closing bridge + cache clone + local prefix assembly**. Required reasoning is charged in full to each hypothetical final output, not amortized across the three draws. Prefix time is taken from saved cumulative source token timestamps, not a linear fraction of whole-run time. Source prefix timestamps end at sampled emission; they are not a separately timed paused online system. Full-source time includes source prefill. No network transfer was used.',
 '', '| Condition | Source prefix s | Receiver prefill s | Receiver reasoning s | Answer s | Bridge/clone/assembly s | Total generated tokens |', '|---|---:|---:|---:|---:|---:|---:|']
 for c in CONDITIONS:
  lines.append(f"| {c} | {mean(c,'source_prefix_accounted_seconds'):.2f} | {mean(c,'receiver_prefill_seconds'):.2f} | {mean(c,'receiver_reasoning_seconds'):.2f} | {mean(c,'answer_seconds'):.2f} | {sum(mean(c,k) for k in ['bridge_seconds','clone_seconds','transfer_seconds']):.4f} | {mean(c,'total_generated_tokens'):.2f} |")
 lines+=['', 'Reasoning-body counts exclude closing-think; answer counts include terminal EOS. Prompt/prefill counts and output character lengths are in `condition_summary.csv`. These stage sums are **reconstructed one-output local latency estimates** from measured components. The experiment ran all source tasks first, then all receiver tasks; it did not measure an end-to-end live handoff service. Model loading and host/Python/checkpoint overhead are separately recorded, not assumed absent in deployment.',
 '', f"Actual benchmark generation took **{work['generation_wall_seconds']/3600:.3f} hours** ({work['generation_wall_seconds']:.3f} s), with no generation restart/recovery. Unique measured reasoning, prefill, answer and setup work totals **{work['unique_measured_stage_and_setup_seconds']/3600:.3f} hours**. Model loads total {sum(work['model_load_seconds'].values()):.3f} s; the remaining {work['generation_unassigned_residual_seconds']:.3f} s is unallocated host/IO/cleanup/scheduling overhead. This does **not** sum all hypothetical per-output costs, which would repeatedly charge reused histories.",
 '', f"Actual emitted tokens: source reasoning {work['actual_unique_generated_emissions']['source_reasoning_emissions']:,}, source answers {work['actual_unique_generated_emissions']['source_answer_emissions']:,}, receiver reasoning {work['actual_unique_generated_emissions']['receiver_reasoning_emissions']:,}, receiver answers {work['actual_unique_generated_emissions']['receiver_answer_emissions']:,}. These actual emission counts include natural closing tokens. Scoring took {work['scoring_elapsed_seconds']/60:.2f} minutes elapsed, with {work['scoring_sum_of_draw_wall_seconds']:.2f} s of summed draw time across two workers. Launch to the initial reporting failure was {work['initial_pipeline_until_report_failure_seconds']/3600:.3f} hours. Downloads, synthetic preflights, tests and final review were additional work, not included in generation elapsed time.",
 '', '**New RunPod charges: $0.** No remote resources were allocated. Local energy, hardware depreciation, GPU-kernel busy seconds/hours and monetary cost per successful answer were not measured. Synchronized MPS wall time is not kernel-busy time. There is no H200 dollar-saving claim and no claim of free compute.',
 '', '## Failures and infrastructure incidents',
 '', '**709 passed, 118 observed failures, 13 missing** across 840 answers. Observed failures: 104 test assertions, 10 CPU timeouts, 2 memory-limit failures, 1 runtime error and 1 syntax error. All are retained. Reasoning caps affected 2/40 source trajectories; receiver caps affected SMALL_ONLY 3/40 and each intermediate fraction 1/40. One SMALL_ONLY answer reached the 4,096-token cap; no other answers did. No early reasoning EOS occurred. Capped source histories still define the full fraction reference; they are not guaranteed complete solutions.',
 '', '**Scoring capacity incident:** all 13 missing outcomes belong to `atcoder/abc364_e`: H25 2, H50 3, H75 3, FULL_TEXT 3, LARGE_ONLY 2. The unchanged scorer classified external SIGKILL as infrastructure missing, not a quality failure. Guest kernel logs record **27 out-of-memory kills** of Python scoring children. The local VM was underprovisioned: **6 GiB total RAM with two concurrent candidates**, while each candidate could use up to 4 GiB address space. The scorer performed its frozen 14 infrastructure retries; 13 remained missing, one retry recovered coverage. This avoidable provisioning error limits the evidence. The results have not been “fixed” by additional retries, changed memory limits or reclassification.',
 '', 'The unchanged scorer uses CPU 12 s, wall 46 s, 4 GiB address space and its existing output/confinement contract. It ran in an offline ARM Linux container/Colima VM with chroot, UID isolation and seccomp. ARM timing differs from the historical x86 scorer. No hidden tests were used to improve answers. Scoring was not rerun during review.',
 '', '**Reporting incident:** the first plot attempted to annotate a null pass rate and failed. The report-only fix displays missingness bounds and preserves null primary estimates. Audit also corrected the exporter’s `receiver_seed` metadata, which initially repeated the answer RNG seed; it now records the actual reasoning seed (null for full-text, which generates no receiver reasoning). Saved generation seeds, outputs, scorer and numeric scores were unchanged. Compact regeneration writes `analysis_draft.md` in its output directory rather than overwriting this reviewed report.',
 '', '## Limitations and conclusion',
 '', '- Forty reused development task clusters are a small, exposed population; three final draws do not remove reasoning-trajectory variance. One reasoning history was sampled per task/condition.',
 '- Missingness is concentrated on a memory-intensive task and is not assumed random. Bounds retain it; supplemental 39-task oracle results are not the primary population.',
 '- Multiple fractions/comparisons, a post-run sensitivity analysis and same-draw oracle make this exploratory. No equivalence margin or fresh confirmation exists.',
 '- Fixed fractions require future total source length. They are retrospective cuts, not an online stopping mechanism. A practical decision rule and its overhead have not been evaluated.',
 '- Receiver cap shrinks with source prefix length. Caps, forced closing and model/backend/CPU architecture differences limit comparisons with historical experiments.',
 '- Sampling kernels, MPS versions, Colima/package builds and hardware may change exact outcomes and timings. Pinned weights/data plus these commands do not promise cross-platform bitwise reproduction. The Ubuntu base digest is pinned but its apt-installed package snapshot is not.',
 '- No serving concurrency/load test, local energy/depreciation estimate, H200 cost estimate, learned router, mapper, sparse mechanism or cache translation was evaluated.',
 '', '**Bottom line:** moving half the large-model reasoning to the smaller model produces a candidate worth further *review*: similar observed quality at materially lower local reconstructed latency than finishing on the large model, but much slower than small-only. The screen does not prove economic or Pareto improvement. Stop here; any confirmation, scoring recovery or online policy work requires a separate decision.',
 '', '## Exact reproduction and verification',
 '', 'From the public research branch, use a clean checkout and an environment with the versions above. No private checkout is needed. `PY` below names that installed environment. The complete retrieval/generation/scoring instructions are in [`REPRODUCE_EARLY_HANDOFF.md`](REPRODUCE_EARLY_HANDOFF.md). Raw benchmark reproduction is costly and is **not** part of this completed review.',
 '', '```sh', 'git clone --branch research/early-handoff-01 https://github.com/ImpossibleComputing/Gearshift.git', 'cd Gearshift', '# For the exact reviewed tree: git checkout <release_commit from MANIFEST.json>', 'export PY=/absolute/path/to/pinned-environment/bin/python', 'export PYTHONDONTWRITEBYTECODE=1', '$PY -m pytest -q', '# Safe numeric-only regeneration (no GPU, no raw benchmark access):', '$PY scripts/early_handoff_report.py --input results/early_handoff_01/analysis_input.json --output data/early_handoff_01/review_regenerated', '$PY scripts/early_handoff_audit.py --compact --input results/early_handoff_01/analysis_input.json --output data/early_handoff_01/review_regenerated', '# audit.json is the retained measured provenance receipt, not inferable from aggregate data:', 'cp results/early_handoff_01/audit.json data/early_handoff_01/review_regenerated/audit.json', '$PY scripts/early_handoff_finalize.py --results data/early_handoff_01/review_regenerated --report data/early_handoff_01/review_regenerated/EARLY_HANDOFF_RESULTS.md', '```',
 '', 'For a fresh **separately authorized** raw reproduction:', '', '```sh', '$PY scripts/fetch_livecodebench.py', '$PY scripts/early_handoff_dependencies.py --workers 4', '$PY scripts/early_handoff_prepare.py', '# Create the bounded local budget ledger exactly as documented in REPRODUCE_EARLY_HANDOFF.md.', '$PY scripts/early_handoff_worker.py preflight --role receiver', '$PY scripts/early_handoff_worker.py preflight --role source', 'colima start --cpu 4 --memory 6 --disk 20 --arch aarch64 --vm-type vz', 'export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"', 'docker build -t gearshift-early-scorer:01 - < configs/early_handoff_01/Scorer.Dockerfile', 'docker run --rm --network none --mount "type=bind,src=$PWD,dst=/repo,readonly" --mount "type=bind,src=$PWD/data/early_handoff_01,dst=/experiment" gearshift-early-scorer:01 python3 scripts/early_handoff_score.py preflight', 'caffeinate -is $PY scripts/early_handoff_pipeline.py', '# Historical pipeline is expected to stop at the original plot bug on generation commit bf85c69.', '# On the reviewed branch the report-only fix avoids that error; no scoring settings changed.', '$PY scripts/early_handoff_report.py', '$PY scripts/early_handoff_audit.py', '```',
 '', 'The commands preserve the **historical 6 GiB/two-worker scoring setup**, including its known capacity risk; they are not a recommendation to repeat that risk. The original stopped pipeline/status/logs remain in ignored storage. A future corrected-capacity scoring run must be separately labeled rather than replacing this evidence.',
 '', 'Review exports: `analysis_input.json`, `per_draw.json/csv`, `per_task.csv`, `task_outcomes.csv`, `condition_summary.csv`, `paired_comparisons.csv`, `summary.json`, `missingness_sensitivity.json`, `audit.json`, `frontier.png` and `verification.json`. The review ZIP includes safe code/config, licenses, provenance and a SHA256 manifest. Original main/progress-02, private archive and website are unchanged. **No new research was launched; this round is complete.**']
 a.report.parent.mkdir(parents=True,exist_ok=True);a.report.write_text('\n'.join(lines)+'\n')
 print('Reviewed report and aggregate CSVs rendered from safe evidence.')
if __name__=='__main__':main()
